version: "3.8"

services:
  postgres:
    container_name: postgres
    env_file:
      - .env
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DOCKER_POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${DOCKER_POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${DOCKER_POSTGRESQL_DATABASE}
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
